spring.application.name=inscripciones
server.port=8080


# Configuracion base de datos
spring.datasource.url=jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=gd4b735e33ce4ce_dbnico_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
spring.datasource.username=CLOUDNATIVE_S1
spring.datasource.password=CloudNativeS1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Configuraciones JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuraciones HikariCP
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariPool

# Session config
spring.session.jdbc.initialize-schema=always
spring.sql.init.mode=always
spring.sql.init.platform=oracle

# Configuracion de login de AWS
logging.level.software.amazon.awssdk=DEBUG
logging.level.io.awspring.cloud=DEBUG